local F = require("jsonata.functions")
local errors = require("jsonata.errors")

describe("functions.helpers (M2c-2 foundations)", function()
  it("def stores arity = min (required arg count)", function()
    assert.are.equal(1, F.boolean.arity)
    assert.are.equal(1, F.string.arity)
    assert.are.equal(1, F.uppercase.arity)
    assert.are.equal(2, F.append.arity)
    assert.is_nil(F.zip.arity)
  end)

  it("truthy treats function values as false", function()
    assert.is_false(F.truthy({ _jsonata_function = true }))
    assert.is_false(F.truthy({ _jsonata_lambda = true, params = {} }))
  end)

  it("new HOF error codes resolve to real messages", function()
    local _, e1 = pcall(errors.raise, "D3050")
    local _, e2 = pcall(errors.raise, "D3138")
    local _, e3 = pcall(errors.raise, "D3139")
    assert.are.equal("D3050", e1.code)
    assert.are.equal("D3138", e2.code)
    assert.are.equal("D3139", e3.code)
    assert.is_not.equal("D3050", e1.message)
    assert.is_truthy(e1.message:find("reduce"))
  end)
end)
