local F = require("jsonata.functions")
local V = require("jsonata.value")

describe("builtins", function()
  it("$string converts values", function()
    assert.are.equal("5", F.string.impl(5))
    assert.are.equal("true", F.string.impl(true))
    -- M5b: $string(undefined) is undefined (jsonata-faithful); '&' coerces to "" inline
    assert.are.equal(V.NOTHING, F.string.impl(V.NOTHING))
    assert.are.equal("null", F.string.impl(V.NULL))
  end)

  it("$string serializes containers (implemented in M2b Task 7)", function()
    assert.are.equal("[1]", F.string.impl(V.array({ 1 })))
  end)

  it("$number parses", function()
    assert.are.equal(5, F.number.impl("5"))
    assert.are.equal(5, F.number.impl(5))
  end)

  it("$number raises D3030 for unparseable strings", function()
    local ok, err = pcall(F.number.impl, "abc")
    assert.is_false(ok)
    assert.are.equal("D3030", err.code)
  end)

  it("$boolean follows JSONata truthiness", function()
    assert.is_true(F.boolean.impl("x"))
    assert.is_false(F.boolean.impl(""))
    assert.is_false(F.boolean.impl(0))
    assert.is_true(F.boolean.impl(V.array({ 1 })))
    assert.is_false(F.boolean.impl(V.array({})))
    assert.is_false(F.boolean.impl(V.NOTHING))
  end)

  it("$not negates truthiness", function()
    assert.is_true(F["not"].impl(""))
    assert.is_false(F["not"].impl("x"))
  end)

  it("$exists detects presence", function()
    assert.is_false(F.exists.impl(V.NOTHING))
    assert.is_true(F.exists.impl(0))
  end)

  it("$count counts sequence length", function()
    assert.are.equal(3, F.count.impl(V.array({ 1, 2, 3 })))
    assert.are.equal(1, F.count.impl(5))
    assert.are.equal(0, F.count.impl(V.NOTHING))
  end)
end)
