local F = require("jsonata.functions")
local V = require("jsonata.value")

describe("numeric functions", function()
  it("$abs/$floor/$ceil", function()
    assert.are.equal(5, F.abs.impl(-5))
    assert.are.equal(3, F.floor.impl(3.7))
    assert.are.equal(4, F.ceil.impl(3.2))
    assert.are.equal(-4, F.floor.impl(-3.2))
  end)

  it("$round uses banker's rounding and precision", function()
    assert.are.equal(2, F.round.impl(2.5))
    assert.are.equal(4, F.round.impl(3.5))
    assert.are.equal(3.14, F.round.impl(3.14159, 2))
    assert.are.equal(120, F.round.impl(123, -1))
  end)

  it("$power/$sqrt", function()
    assert.are.equal(8, F.power.impl(2, 3))
    assert.are.equal(3, F.sqrt.impl(9))
  end)

  it("$formatBase", function()
    assert.are.equal("ff", F.formatBase.impl(255, 16))
    assert.are.equal("101", F.formatBase.impl(5, 2))
  end)

  it("$number parses radix prefixes per spec", function()
    assert.are.equal(18, F.number.impl("0x12"))
    assert.are.equal(5, F.number.impl("0B101"))
    assert.are.equal(10, F.number.impl("0O12"))
  end)
end)
