local F = require("jsonata.functions")
local V = require("jsonata.value")

describe("url functions", function()
  it("$base64encode / $base64decode round-trip", function()
    assert.are.equal("aGVsbG86d29ybGQ=", F.base64encode.impl("hello:world"))
    assert.are.equal("hello:world", F.base64decode.impl("aGVsbG86d29ybGQ="))
  end)

  it("$base64encode / $base64decode return undefined for undefined input", function()
    assert.are.same(V.NOTHING, F.base64encode.impl(nil))
    assert.are.same(V.NOTHING, F.base64decode.impl(nil))
  end)

  it("$encodeUrlComponent / $decodeUrlComponent round-trip", function()
    assert.are.equal("a%20b%2Fc", F.encodeUrlComponent.impl("a b/c"))
    assert.are.equal("a b/c", F.decodeUrlComponent.impl("a%20b%2Fc"))
  end)

  it("$encodeUrl keeps reserved chars, encodes spaces", function()
    assert.are.equal("http://x/a%20b", F.encodeUrl.impl("http://x/a b"))
    assert.are.equal("http://x/a b", F.decodeUrl.impl("http://x/a%20b"))
  end)

  it("$decodeUrl reports malformed percent-encoded UTF-8", function()
    local ok, err = pcall(F.decodeUrl.impl, "%E0%A4%A")
    assert.is_false(ok)
    assert.are.equal("D3140", err.code)
  end)

  it("$decodeUrlComponent reports malformed percent-encoded UTF-8", function()
    local ok, err = pcall(F.decodeUrlComponent.impl, "%E0%A4%A")
    assert.is_false(ok)
    assert.are.equal("D3140", err.code)
  end)
end)
