local A = require("jsonata.adapter")
local V = require("jsonata.value")

describe("adapter: input normalization", function()
  it("maps scalars unchanged", function()
    assert.are.equal(3, A.from_lua(3))
    assert.are.equal("s", A.from_lua("s"))
    assert.are.equal(true, A.from_lua(true))
    assert.is_true(V.is_nothing(A.from_lua(nil)))
  end)

  it("treats contiguous 1..n tables as arrays", function()
    local a = A.from_lua({ 10, 20, 30 })
    assert.is_true(V.is_array(a))
    assert.are.equal(20, a[2])
  end)

  it("treats string-keyed tables as ordered objects", function()
    local o = A.from_lua({ name = "Bob" })
    assert.is_true(V.is_object(o))
    assert.are.equal("Bob", V.obj_get(o, "name"))
  end)

  it("treats empty tables as objects by default", function()
    assert.is_true(V.is_object(A.from_lua({})))
  end)

  it("maps the NULL output marker back to internal NULL", function()
    assert.is_true(V.is_null(A.from_lua(A.NULL)))
  end)

  it("recurses into nested structures", function()
    local v = A.from_lua({ items = { 1, 2 } })
    assert.is_true(V.is_object(v))
    local items = V.obj_get(v, "items")
    assert.is_true(V.is_array(items))
    assert.are.equal(2, items[2])
  end)
end)

describe("adapter: output conversion", function()
  it("converts arrays and objects back to plain tables", function()
    local o = V.object()
    V.obj_set(o, "a", V.array({ 1, 2 }))
    local out = A.to_lua(o)
    assert.are.same({ 1, 2 }, out.a)
  end)

  it("maps NOTHING to nil and NULL to a recognizable marker", function()
    assert.is_nil(A.to_lua(V.NOTHING))
    assert.are.equal(A.NULL, A.to_lua(V.NULL))
  end)
end)
