local errors = require("jsonata.errors")
local E = require("jsonata.evaluator")

describe("M5d: M.is_function + T2006", function()
  it("M.is_function recognizes lambdas and builtins, rejects data", function()
    assert.is_true(E.is_function({ _jsonata_lambda = true }))
    assert.is_true(E.is_function({ _jsonata_function = true }))
    assert.is_falsy(E.is_function(5))
    assert.is_falsy(E.is_function("x"))
    assert.is_falsy(E.is_function({ a = 1 }))
    assert.is_falsy(E.is_function(nil))
  end)

  it("defines the T2006 template", function()
    local ok, e = pcall(errors.raise, "T2006", { value = 3 })
    assert.is_false(ok)
    assert.are.equal("T2006", e.code)
    assert.is_not_nil(e.message:find("function application", 1, true))
  end)
end)
