local Environment = require("jsonata.environment")

describe("environment", function()
  it("binds and looks up in the current frame", function()
    local env = Environment.new()
    env:bind("x", 42)
    assert.are.equal(42, env:lookup("x"))
  end)

  it("falls back to the enclosing frame", function()
    local root = Environment.new()
    root:bind("a", 1)
    local child = root:create_frame()
    child:bind("b", 2)
    assert.are.equal(1, child:lookup("a"))
    assert.are.equal(2, child:lookup("b"))
    assert.is_nil(root:lookup("b"))
  end)

  it("shadows outer bindings", function()
    local root = Environment.new()
    root:bind("a", 1)
    local child = root:create_frame()
    child:bind("a", 9)
    assert.are.equal(9, child:lookup("a"))
    assert.are.equal(1, root:lookup("a"))
  end)
end)
