local errors = require("jsonata.errors")

describe("errors", function()
  it("raises a structured error carrying code/position/token", function()
    local ok, err = pcall(function()
      errors.raise("S0203", { position = 5, token = ")" })
    end)
    assert.is_false(ok)
    assert.are.equal("S0203", err.code)
    assert.are.equal(5, err.position)
    assert.are.equal(")", err.token)
    assert.is_string(err.message)
  end)

  it("includes value for runtime errors", function()
    local ok, err = pcall(function()
      errors.raise("T0410", { value = 3 })
    end)
    assert.is_false(ok)
    assert.are.equal(3, err.value)
  end)

  it("is detectable via is_error", function()
    local ok, err = pcall(function()
      errors.raise("S0211", { position = 1 })
    end)
    assert.is_true(errors.is_error(err))
    assert.is_false(errors.is_error("plain string"))
  end)
end)
