local errors = require("jsonata.errors")

describe("errors", function()
  it("raises a structured error carrying code/position/token", function()
    local ok, err = pcall(function()
      errors.raise("S0203", { position = 5, token = ")" })
    end)
    assert.is_false(ok)
    assert.are.equal("S0203", err.code)
    assert.are.equal(5, err.position)
    assert.are.equal(")", err.token)
    assert.is_string(err.message)
  end)

  it("includes value for runtime errors", function()
    local ok, err = pcall(function()
      errors.raise("T0410", { value = 3 })
    end)
    assert.is_false(ok)
    assert.are.equal(3, err.value)
  end)

  it("is detectable via is_error", function()
    local ok, err = pcall(function()
      errors.raise("S0211", { position = 1 })
    end)
    assert.is_true(errors.is_error(err))
    assert.is_false(errors.is_error("plain string"))
  end)
end)

describe("errors: order-by codes (M2c-3b)", function()
  local errors = require("jsonata.errors")

  it("T2007 and T2008 resolve to messages", function()
    local _, e7 = pcall(errors.raise, "T2007", { value = 1, value2 = "x" })
    local _, e8 = pcall(errors.raise, "T2008", { value = {} })
    assert.are.equal("T2007", e7.code)
    assert.are.equal("T2008", e8.code)
    assert.is_not.equal("T2007", e7.message)
  end)

  it("raise passes through value2", function()
    local _, e = pcall(errors.raise, "T2007", { value = 1, value2 = "x" })
    assert.are.equal(1, e.value)
    assert.are.equal("x", e.value2)
  end)
end)

describe("errors: group-by codes (M2c-4a)", function()
  local errors = require("jsonata.errors")

  it("T1003 and D1009 resolve to messages", function()
    local _, e1 = pcall(errors.raise, "T1003", { value = 5 })
    local _, e2 = pcall(errors.raise, "D1009", { value = "k" })
    assert.are.equal("T1003", e1.code)
    assert.are.equal("D1009", e2.code)
    assert.is_not.equal("T1003", e1.message)
  end)
end)

describe("errors: transform codes (M2c-4b)", function()
  local errors = require("jsonata.errors")

  it("T2011 and T2012 resolve to messages", function()
    local _, e1 = pcall(errors.raise, "T2011", { value = 5 })
    local _, e2 = pcall(errors.raise, "T2012", { value = 5 })
    assert.are.equal("T2011", e1.code)
    assert.are.equal("T2012", e2.code)
    assert.is_not.equal("T2011", e1.message)
  end)
end)

describe("errors: range codes (M2d)", function()
  local errors = require("jsonata.errors")

  it("T2003, T2004, D2014 resolve to messages", function()
    local _, e1 = pcall(errors.raise, "T2003", { value = 1.5 })
    local _, e2 = pcall(errors.raise, "T2004", { value = 1.5 })
    local _, e3 = pcall(errors.raise, "D2014", { value = 99 })
    assert.are.equal("T2003", e1.code)
    assert.are.equal("T2004", e2.code)
    assert.are.equal("D2014", e3.code)
    assert.is_not.equal("T2003", e1.message)
  end)
end)
