local jsonata = require("jsonata")
local function run(src, input)
  return jsonata.compile(src):evaluate(input)
end

describe("M8b: $formatInteger decimal-digit-pattern", function()
  it("padding + mandatory/optional digits", function()
    assert.are.equal("123", run("$formatInteger(123, '000')"))
    assert.are.equal("0123", run("$formatInteger(123, '0000')"))
    assert.are.equal("-0003", run("$formatInteger(-3, '0000')"))
    assert.are.equal("1234", run("$formatInteger(1234, '###0')"))
    assert.are.equal("12", run("$formatInteger(12, '###0')"))
    assert.are.equal("12", run("$formatInteger(12.6, '###0')"))
  end)
  it("grouping regular + irregular", function()
    assert.are.equal("12", run("$formatInteger(12, '#,##0')"))
    assert.are.equal("1,200", run("$formatInteger(1200, '#,##0')"))
    assert.are.equal("12,345,678", run("$formatInteger(12345678, '#,##0')"))
    assert.are.equal("1234:567,890", run("$formatInteger(1234567890, '#:###,##0')"))
    assert.are.equal("12345,67,890", run("$formatInteger(1234567890, '##,##,##0')"))
  end)
  it("large integers render without exponent", function()
    assert.are.equal("1000000000000000", run("$formatInteger(1000000000000000, '0')"))
    assert.are.equal("123,456,789,012,345", run("$formatInteger(123456789012345, '#,##0')"))
  end)
  it("ordinal suffix + teen exception", function()
    assert.are.equal("1st", run("$formatInteger(1, '0;o')"))
    assert.are.equal("123rd", run("$formatInteger(123, '000;o')"))
    assert.are.equal("28th", run("$formatInteger(28, '#0;o')"))
    assert.are.equal("12th", run("$formatInteger(12, '###0;o')"))
  end)
  it("unicode digit families", function()
    assert.are.equal("١٢٣٤٠", run("$formatInteger(12340, '###١')"))
    assert.are.equal("１２３４０", run("$formatInteger(12340, '###０')"))
  end)
  it("D3131 mixed digit groups", function()
    local ok, err = pcall(run, "$formatInteger(12340, '##0０')")
    assert.is_false(ok)
    assert.are.equal("D3131", err.code)
  end)
  it("undefined -> undefined", function()
    assert.is_nil(run("$formatInteger(blah, '0')", {}))
  end)
end)

describe("M8b: $parseInteger decimal-digit-pattern", function()
  it("digits + padding + grouping", function()
    assert.are.equal(123, run("$parseInteger('123', '000')"))
    assert.are.equal(123, run("$parseInteger('0123', '0000')"))
    assert.are.equal(1234, run("$parseInteger('1234', '###0')"))
    assert.are.equal(1200, run("$parseInteger('1,200', '#,##0')"))
    assert.are.equal(12345678, run("$parseInteger('12,345,678', '#,##0')"))
    assert.are.equal(1234567890, run("$parseInteger('1234:567,890', '#:###,##0')"))
    assert.are.equal(1234567890, run("$parseInteger('12345,67,890', '##,##,##0')"))
  end)
  it("ordinal + families", function()
    assert.are.equal(123, run("$parseInteger('123rd', '000;o')"))
    assert.are.equal(28, run("$parseInteger('28th', '#0;o')"))
    assert.are.equal(12340, run("$parseInteger('١٢٣٤٠', '###١')"))
    assert.are.equal(12340, run("$parseInteger('１２３４０', '###０')"))
  end)
  it("undefined -> undefined", function()
    assert.is_nil(run("$parseInteger(blah, '0')", {}))
  end)
end)

describe("M8b: roman + letters", function()
  it("formatInteger roman", function()
    assert.are.equal("", run("$formatInteger(0, 'I')"))
    assert.are.equal("MCMLXXXIV", run("$formatInteger(1984, 'I')"))
    assert.are.equal("xcix", run("$formatInteger(99, 'i')"))
  end)
  it("parseInteger roman", function()
    assert.are.equal(0, run("$parseInteger('', 'I')"))
    assert.are.equal(1984, run("$parseInteger('MCMLXXXIV', 'I')"))
    assert.are.equal(99, run("$parseInteger('xcix', 'i')"))
  end)
  it("formatInteger letters", function()
    assert.are.equal("A", run("$formatInteger(1, 'A')"))
    assert.are.equal("l", run("$formatInteger(12, 'a')"))
    assert.are.equal("z", run("$formatInteger(26, 'a')"))
    assert.are.equal("aa", run("$formatInteger(27, 'a')"))
    assert.are.equal("KN", run("$formatInteger(300, 'A')"))
    assert.are.equal("FZPH", run("$formatInteger(123456, 'A')"))
  end)
  it("parseInteger letters", function()
    assert.are.equal(1, run("$parseInteger('A', 'A')"))
    assert.are.equal(12, run("$parseInteger('l', 'a')"))
    assert.are.equal(26, run("$parseInteger('z', 'a')"))
    assert.are.equal(27, run("$parseInteger('aa', 'a')"))
    assert.are.equal(300, run("$parseInteger('KN', 'A')"))
    assert.are.equal(123456, run("$parseInteger('FZPH', 'A')"))
  end)
  it("D3130 sequence", function()
    local ok, err = pcall(run, "$formatInteger(123456, 'α')")
    assert.is_false(ok)
    assert.are.equal("D3130", err.code)
    local ok2, err2 = pcall(run, "$parseInteger('50', '#')")
    assert.is_false(ok2)
    assert.are.equal("D3130", err2.code)
  end)
end)

describe("M8b: words cardinal", function()
  it("basic + decades + hundreds + magnitudes", function()
    assert.are.equal("twelve", run("$formatInteger(12, 'w')"))
    assert.are.equal("twenty", run("$formatInteger(20, 'w')"))
    assert.are.equal("thirty-four", run("$formatInteger(34, 'w')"))
    assert.are.equal("NINETY-NINE", run("$formatInteger(99, 'W')"))
    assert.are.equal("one hundred", run("$formatInteger(100, 'w')"))
    assert.are.equal("FIVE HUNDRED AND FIFTY-FIVE", run("$formatInteger(555, 'W')"))
    assert.are.equal("Five Hundred and Fifty-Five", run("$formatInteger(555, 'Ww')"))
    assert.are.equal("nine hundred and nineteen", run("$formatInteger(919, 'w')"))
    assert.are.equal("one thousand", run("$formatInteger(1000, 'w')"))
    assert.are.equal("three thousand, seven hundred and thirty", run("$formatInteger(3730, 'w')"))
    assert.are.equal("four million, three hundred and twenty-seven thousand, seven hundred and thirty", run("$formatInteger(4327730, 'w')"))
    assert.are.equal("one trillion and one", run("$formatInteger(1000000000001, 'w')"))
    assert.are.equal("one thousand trillion", run("$formatInteger(1000000000000000, 'w')"))
    assert.are.equal("ten billion trillion trillion trillion", run("$formatInteger(1e46, 'w')"))
  end)
end)
describe("M8b: words ordinal", function()
  it("ordinal forms", function()
    assert.are.equal("twelfth", run("$formatInteger(12, 'w;o')"))
    assert.are.equal("twentieth", run("$formatInteger(20, 'w;o')"))
    assert.are.equal("thirty-fourth", run("$formatInteger(34, 'w;o')"))
    assert.are.equal("NINETY-NINTH", run("$formatInteger(99, 'W;o')"))
    assert.are.equal("one hundredth", run("$formatInteger(100, 'w;o')"))
    assert.are.equal("seven hundred and thirtieth", run("$formatInteger(730, 'w;o')"))
    assert.are.equal("one thousandth", run("$formatInteger(1000, 'w;o')"))
    assert.are.equal("one trillion and first", run("$formatInteger(1000000000001, 'w;o')"))
  end)
end)
describe("M8b: words parse", function()
  it("cardinal + ordinal + title", function()
    assert.are.equal(12, run("$parseInteger('twelve', 'w')"))
    assert.are.equal(34, run("$parseInteger('thirty-four', 'w')"))
    assert.are.equal(99, run("$parseInteger('NINETY-NINE', 'W')"))
    assert.are.equal(555, run("$parseInteger('Five Hundred and Fifty-Five', 'Ww')"))
    assert.are.equal(3730, run("$parseInteger('three thousand, seven hundred and thirty', 'w')"))
    assert.are.equal(1000000000001, run("$parseInteger('one trillion and one', 'w')"))
    assert.are.equal(1000000000000000, run("$parseInteger('one thousand trillion', 'w')"))
    assert.are.equal(12, run("$parseInteger('twelfth', 'w;o')"))
    assert.are.equal(20, run("$parseInteger('twentieth', 'w;o')"))
    assert.are.equal(733, run("$parseInteger('Seven Hundred and Thirty-Third', 'Ww;o')"))
    assert.are.equal(1000000000001, run("$parseInteger('one trillion and first', 'w;o')"))
  end)

  it("unrecognized words token -> NaN (not a crash), matching oracle", function()
    local r = run("$parseInteger('foo', 'w')")
    assert.is_true(type(r) == "number" and r ~= r) -- NaN
    local r2 = run("$parseInteger('-twelve', 'w')")
    assert.is_true(type(r2) == "number" and r2 ~= r2)
    -- valid input still works
    assert.are.equal(34, run("$parseInteger('thirty-four', 'w')"))
  end)
end)
