local jsonata = require("jsonata")
local parser = require("jsonata.parser")

describe("M6c parser: @ / # bind focus/index on the last flat step", function()
  it("a@$x.b flattens to [a(focus x), b] with tuple set", function()
    local ast = parser.parse("a@$x.b")
    assert.are.equal("path", ast.type)
    assert.are.equal("x", ast.steps[1].focus)
    assert.is_true(ast.steps[1].tuple)
    assert.are.equal("b", ast.steps[2].value)
    assert.is_nil(ast.steps[2].focus)
  end)

  it("$#$pos wraps a single step with index set", function()
    local ast = parser.parse("$#$pos")
    assert.are.equal("path", ast.type)
    assert.are.equal("pos", ast.steps[1].index)
    assert.is_true(ast.steps[1].tuple)
  end)

  it("a.b@$l.c@$m keeps a flat 3-step path with two focuses", function()
    local ast = parser.parse("a.b@$l.c@$m")
    assert.are.equal(3, #ast.steps)
    assert.are.equal("l", ast.steps[2].focus)
    assert.are.equal("m", ast.steps[3].focus)
  end)
end)

describe("M6c parser: validation errors", function()
  it("@ with a non-variable rhs raises S0214 (token @)", function()
    local ok, err = pcall(parser.parse, "Account.Order@o.Product")
    assert.is_false(ok)
    assert.are.equal("S0214", err.code)
    assert.are.equal("@", err.token)
  end)

  it("# with a non-variable rhs raises S0214 (token #)", function()
    local ok, err = pcall(parser.parse, "Account.Order@$o#i.Product")
    assert.is_false(ok)
    assert.are.equal("S0214", err.code)
    assert.are.equal("#", err.token)
  end)

  it("@ after a predicate raises S0215", function()
    local ok, err = pcall(parser.parse, "Account.Order[1]@$o.Product")
    assert.is_false(ok)
    assert.are.equal("S0215", err.code)
  end)

  it("@ after a sort raises S0216", function()
    local ok, err = pcall(parser.parse, "Account.Order^(>OrderID)@$o.Product")
    assert.is_false(ok)
    assert.are.equal("S0216", err.code)
  end)

  it("# after a sort/filter does NOT raise (it indexes the step)", function()
    assert.has_no.errors(function()
      parser.parse("$^($)#$pos")
    end)
    assert.has_no.errors(function()
      parser.parse("$[[1..4]]#$pos")
    end)
  end)
end)
