local jsonata = require("jsonata")
local function run(src, input)
  return jsonata.compile(src):evaluate(input)
end

describe("M6b A-2: quoted-string path step selects a field", function()
  it('foo."bar" selects the field bar', function()
    assert.are.equal(7, run('foo."bar"', { foo = { bar = 7 } }))
  end)
  it("a top-level string is still the literal", function()
    assert.are.equal("bar", run('"bar"', { foo = { bar = 7 } }))
  end)
  it('foo."bar" over a non-object foo is undefined (faithful)', function()
    assert.is_nil(run('foo."bar"', { foo = 5 }))
  end)
  it("a standalone string with a predicate stays a literal", function()
    assert.are.equal("Red", run('"Red"[$$ = "Bus"]', "Bus"))
    assert.is_nil(run('"Red"[$$ = "Car"]', "Bus"))
  end)
  it("a first-position quoted string in a path is also a field selector", function()
    assert.are.equal(1, run('"x"."y"', { x = { y = 1 } }))
    assert.are.equal(1, run('"x".y', { x = { y = 1 } }))
    assert.are.equal(99, run('"a"."b"."c"', { a = { b = { c = 99 } } }))
  end)

  it("a standalone string / parenthesized literal is unaffected for non-path uses", function()
    assert.are.equal("bar", run('"bar"', {}))
    assert.are.equal("Red", run('"Red"[$$ = "Bus"]', "Bus"))
  end)
end)

describe("M6b A-4: trailing ; in a block", function()
  it("tolerates a trailing ; before )", function()
    assert.are.equal(2, run("(1; 2;)"))
  end)
  it("( a; ) yields a", function()
    assert.are.equal(1, run("(1;)"))
  end)
  it("empty () is unaffected", function()
    assert.is_nil(run("()"))
  end)
end)

describe("M6b []: keepArray (any step keeps the final array)", function()
  it("a.b[] forces a single result into an array", function()
    assert.are.same({ 1 }, run("a.b[]", { a = { b = 1 } }))
  end)
  it("a.b[] is a no-op on a multi-element result", function()
    assert.are.same({ 1, 2 }, run("a.b[]", { a = { { b = 1 }, { b = 2 } } }))
  end)
  it("a mid-path [] keeps the final array (a[].b)", function()
    assert.are.same({ 1 }, run("a[].b", { a = { b = 1 } }))
  end)
  it("a mid-path [] with a predicate keeps the final array (case037 shape)", function()
    assert.are.same({ 1 }, run('x[k="a"][].v', { x = { { k = "a", v = 1 } } }))
  end)
  it("foo[] over a missing field is undefined, not []", function()
    assert.is_nil(run("foo[]", {}))
  end)
  it("foo[][] is idempotent", function()
    assert.are.same({ 5 }, run("foo[][]", { foo = 5 }))
  end)
  it("a normal path still unwraps a single result (regression)", function()
    assert.are.equal(1, run("a.b", { a = { b = 1 } }))
  end)
end)
