local jsonata = require("jsonata")
local function run(src, input)
  return jsonata.compile(src):evaluate(input)
end

describe("M6b A-2: quoted-string path step selects a field", function()
  it('foo."bar" selects the field bar', function()
    assert.are.equal(7, run('foo."bar"', { foo = { bar = 7 } }))
  end)
  it("a top-level string is still the literal", function()
    assert.are.equal("bar", run('"bar"', { foo = { bar = 7 } }))
  end)
  it("foo.\"bar\" over a non-object foo is undefined (faithful)", function()
    assert.is_nil(run('foo."bar"', { foo = 5 }))
  end)
  it("a standalone string with a predicate stays a literal", function()
    assert.are.equal("Red", run('"Red"[$$ = "Bus"]', "Bus"))
    assert.is_nil(run('"Red"[$$ = "Car"]', "Bus"))
  end)
end)

describe("M6b A-4: trailing ; in a block", function()
  it("tolerates a trailing ; before )", function()
    assert.are.equal(2, run("(1; 2;)"))
  end)
  it("( a; ) yields a", function()
    assert.are.equal(1, run("(1;)"))
  end)
  it("empty () is unaffected", function()
    assert.is_nil(run("()"))
  end)
end)
