local jsonata = require("jsonata")
local function run(src, input)
  return jsonata.compile(src):evaluate(input)
end

describe("M6a C-1: $$ root context", function()
  it("$$ resolves to the root input", function()
    assert.are.same({ a = 1 }, run("$$", { a = 1 }))
  end)
  it("$$ reaches root from a nested path step", function()
    assert.are.same({ a = { b = 2 } }, run("a.$$", { a = { b = 2 } }))
  end)
  it("$$.field indexes the root", function()
    assert.are.equal(1, run("$$.a", { a = 1 }))
  end)
  it("$ (current context) still works", function()
    assert.are.equal(5, run("a.$", { a = 5 }))
    assert.are.same({ x = 1 }, run("$", { x = 1 }))
  end)
end)

describe("M6a B-3: $keys/$spread empty & scalar", function()
  it("$keys of an empty result is undefined, not []", function()
    assert.is_nil(run("$keys(5)"))
    assert.is_nil(run("$keys({})"))
  end)
  it("$keys still returns the keys of an object", function()
    assert.are.same({ "a", "b" }, run('$keys({"a":1, "b":2})'))
  end)
  it("$spread echoes a scalar argument", function()
    assert.are.equal(5, run("$spread(5)"))
    assert.is_true(run("$spread(true)"))
  end)
  it("$spread still spreads an object", function()
    assert.are.same({ { a = 1 } }, run('$spread({"a":1})'))
  end)
end)
