local parser = require("jsonata.parser")

describe("parser: literals and names", function()
  it("parses a number literal", function()
    local ast = parser.parse("42")
    assert.are.equal("number", ast.type)
    assert.are.equal(42, ast.value)
  end)

  it("parses string, boolean, null literals", function()
    assert.are.equal("hi", parser.parse([["hi"]]).value)
    assert.are.equal(true, parser.parse("true").value)
    assert.are.equal("boolean", parser.parse("false").type)
    assert.are.equal("null", parser.parse("null").type)
  end)

  it("parses a bare name", function()
    local ast = parser.parse("foo")
    assert.are.equal("name", ast.type)
    assert.are.equal("foo", ast.value)
  end)

  it("parses a variable", function()
    local ast = parser.parse("$x")
    assert.are.equal("variable", ast.type)
    assert.are.equal("x", ast.value)
  end)

  it("raises on trailing garbage", function()
    local errors = require("jsonata.errors")
    local ok, err = pcall(parser.parse, "1 2")
    assert.is_false(ok)
    assert.is_true(errors.is_error(err))
  end)
end)

describe("parser: operators", function()
  it("respects arithmetic precedence", function()
    local ast = parser.parse("2 + 3 * 4")
    assert.are.equal("binary", ast.type)
    assert.are.equal("+", ast.value)
    assert.are.equal(2, ast.lhs.value)
    assert.are.equal("*", ast.rhs.value)
    assert.are.equal(3, ast.rhs.lhs.value)
  end)

  it("parses unary minus", function()
    local ast = parser.parse("-5")
    assert.are.equal("unary", ast.type)
    assert.are.equal("-", ast.value)
    assert.are.equal(5, ast.expression.value)
  end)

  it("parses comparison, boolean and concat", function()
    assert.are.equal("=", parser.parse("a = b").value)
    assert.are.equal("and", parser.parse("a and b").value)
    assert.are.equal("&", parser.parse([[a & b]]).value)
  end)

  it("parses parenthesized grouping", function()
    local ast = parser.parse("(2 + 3) * 4")
    assert.are.equal("*", ast.value)
    assert.are.equal("+", ast.lhs.value)
  end)

  it("right-associates assignment", function()
    local ast = parser.parse("$a := $b := 1")
    assert.are.equal("bind", ast.type)
    assert.are.equal("bind", ast.rhs.type)
  end)

  it("rejects the out-of-scope `in` operator with a structured error", function()
    local errs = require("jsonata.errors")
    local ok, err = pcall(parser.parse, "a in b")
    assert.is_false(ok)
    assert.is_true(errs.is_error(err))
  end)
end)

describe("parser: paths", function()
  it("flattens dotted paths into a single path node", function()
    local ast = parser.parse("a.b.c")
    assert.are.equal("path", ast.type)
    assert.are.equal(3, #ast.steps)
    assert.are.equal("a", ast.steps[1].value)
    assert.are.equal("c", ast.steps[3].value)
  end)

  it("keeps a single name as a plain name (no path)", function()
    assert.are.equal("name", parser.parse("a").type)
  end)

  it("treats variable.name as a path with variable first step", function()
    local ast = parser.parse("$x.name")
    assert.are.equal("path", ast.type)
    assert.are.equal("variable", ast.steps[1].type)
    assert.are.equal("name", ast.steps[2].type)
  end)
end)

describe("parser: constructors and predicates", function()
  it("parses an array constructor", function()
    local ast = parser.parse("[1, 2, 3]")
    assert.are.equal("array", ast.type)
    assert.are.equal(3, #ast.expressions)
  end)

  it("parses an object constructor preserving pairs", function()
    local ast = parser.parse([[{"a": 1, "b": 2}]])
    assert.are.equal("object", ast.type)
    assert.are.equal(2, #ast.pairs)
    assert.are.equal("a", ast.pairs[1][1].value)
    assert.are.equal(1, ast.pairs[1][2].value)
  end)

  it("attaches a predicate to a path step", function()
    local ast = parser.parse("items[0]")
    assert.are.equal("path", ast.type)
    assert.is_table(ast.steps[1].predicate)
    assert.are.equal(0, ast.steps[1].predicate[1].value)
  end)

  it("parses a ternary conditional", function()
    local ast = parser.parse("a ? b : c")
    assert.are.equal("condition", ast.type)
    assert.are.equal("a", ast.condition.value)
    assert.are.equal("b", ast.then_expr.value)
    assert.are.equal("c", ast.else_expr.value)
  end)
end)

describe("parser: lambdas", function()
  it("parses a lambda with one param", function()
    local ast = parser.parse("function($x){ $x + 1 }")
    assert.are.equal("lambda", ast.type)
    assert.are.same({ "x" }, ast.params)
    assert.are.equal("binary", ast.body.type)
  end)

  it("parses a lambda with no params", function()
    local ast = parser.parse("function(){ 1 }")
    assert.are.equal("lambda", ast.type)
    assert.are.equal(0, #ast.params)
  end)

  it("parses a lambda with multiple params", function()
    local ast = parser.parse("function($a, $b){ $a }")
    assert.are.same({ "a", "b" }, ast.params)
  end)
end)

describe("parser: apply operator", function()
  it("parses ~> as an apply node", function()
    local ast = parser.parse("5 ~> $string")
    assert.are.equal("apply", ast.type)
    assert.are.equal(5, ast.lhs.value)
    assert.are.equal("variable", ast.rhs.type)
  end)
end)

describe("parser: placeholder", function()
  it("parses ? as a placeholder argument", function()
    local ast = parser.parse("$substring(?, 0, 2)")
    assert.are.equal("function", ast.type)
    assert.are.equal("placeholder", ast.arguments[1].type)
  end)
end)

describe("parser: order-by ^", function()
  it("parses $^(age) as a path with a sort step (ascending)", function()
    local ast = parser.parse("$^(age)")
    assert.are.equal("path", ast.type)
    assert.are.equal(2, #ast.steps)
    assert.are.equal("variable", ast.steps[1].type)
    local sort = ast.steps[2]
    assert.are.equal("sort", sort.type)
    assert.are.equal(1, #sort.terms)
    assert.is_false(sort.terms[1].descending)
    assert.are.equal("name", sort.terms[1].expression.type)
    assert.are.equal("age", sort.terms[1].expression.value)
  end)

  it("parses descending ^(>age)", function()
    local ast = parser.parse("$^(>age)")
    assert.is_true(ast.steps[2].terms[1].descending)
  end)

  it("parses multiple sort terms ^(a, b)", function()
    local ast = parser.parse("$^(a, b)")
    local sort = ast.steps[2]
    assert.are.equal(2, #sort.terms)
    assert.are.equal("a", sort.terms[1].expression.value)
    assert.are.equal("b", sort.terms[2].expression.value)
  end)
end)

describe("parser: group-by {}", function()
  it("parses a{k: v} as a path with a group step", function()
    local ast = parser.parse("a{k: v}")
    assert.are.equal("path", ast.type)
    assert.are.equal(2, #ast.steps)
    assert.are.equal("name", ast.steps[1].type)
    local grp = ast.steps[2]
    assert.are.equal("group", grp.type)
    assert.are.equal(1, #grp.pairs)
    assert.are.equal("k", grp.pairs[1][1].value)
    assert.are.equal("v", grp.pairs[1][2].value)
  end)

  it("parses multiple key:value pairs", function()
    local ast = parser.parse("a{k1: v1, k2: v2}")
    assert.are.equal(2, #ast.steps[2].pairs)
    assert.are.equal("k2", ast.steps[2].pairs[2][1].value)
  end)

  it("keeps a leading {...} as an object literal (nud, not group)", function()
    assert.are.equal("object", parser.parse("{k: v}").type)
  end)
end)

describe("parser: transform |...|", function()
  it("parses a bare |pattern|update| into a transform node", function()
    local ast = parser.parse("|a|{}|")
    assert.are.equal("transform", ast.type)
    assert.are.equal("name", ast.pattern.type)
    assert.are.equal("a", ast.pattern.value)
    assert.are.equal("object", ast.update.type)
    assert.is_nil(ast.delete)
  end)

  it("parses an optional delete clause", function()
    local ast = parser.parse("|a|{},['x']|")
    assert.are.equal("array", ast.delete.type)
  end)

  it("parses as the rhs of ~>", function()
    local ast = parser.parse("$ ~> |a|{}|")
    assert.are.equal("apply", ast.type)
    assert.are.equal("transform", ast.rhs.type)
  end)
end)
