local jsonata = require("jsonata")
local parser = require("jsonata.parser")
local function run(src, input)
  return jsonata.compile(src):evaluate(input)
end

describe("M7a: regex literal lexing + / disambiguation", function()
  it("parses /ab+/ as a regex node", function()
    local ast = parser.parse("/ab+/")
    assert.are.equal("regex", ast.type)
    assert.are.equal("ab+", ast.source)
    assert.are.equal("", ast.flags)
  end)
  it("captures i/m flags", function()
    assert.are.equal("i", parser.parse("/ab+/i").flags)
  end)
  it("/ after a value is division, not a regex", function()
    assert.are.equal(2, run("4/2"))
    assert.are.equal(5, run("($x := 10; $x/2)"))
    assert.are.equal(5, run("x/2", { x = 10 }))
    assert.are.equal(1, run("(1+1)/2"))
  end)
  it("empty // raises S0301", function()
    local ok, err = pcall(parser.parse, "//")
    assert.is_false(ok)
    assert.are.equal("S0301", err.code)
  end)
  it("unterminated /re raises S0302", function()
    local ok, err = pcall(parser.parse, "/unterminated")
    assert.is_false(ok)
    assert.are.equal("S0302", err.code)
  end)
  it("a closing / inside [..] does not end the regex (depth tracking)", function()
    assert.are.equal("[/]", parser.parse("/[/]/").source)
  end)
end)

describe("M7a: regex value (callable function)", function()
  it("a regex is a function value", function()
    assert.are.equal("function", run("$type(/b+/)"))
  end)
  it("applying a regex returns a match object", function()
    assert.are.equal("bb", run('($m := /b+/; $m("abbc")).match'))
  end)
  it("captures appear in groups (0-indexed array access)", function()
    assert.are.equal("bb", run('($m := /a(b+)/; $m("xabbc")).groups[0]'))
  end)
  it("the i flag is case-insensitive", function()
    assert.are.equal("Hat", run('($m := /hat/i; $m("a Hat here")).match'))
  end)
  it("no match returns undefined", function()
    assert.is_nil(run('($m := /z+/; $m("abc"))'))
  end)
end)

describe("M7a: $contains / $split with regex", function()
  it("$contains with regex", function()
    assert.is_true(run('$contains("ababbxabbcc", /ab+/)'))
    assert.is_false(run('$contains("ababbxabbcc", /ax+/)'))
    assert.is_true(run('$contains("a Hat", /hat/i)'))
  end)
  it("$contains with a string still works", function()
    assert.is_true(run('$contains("Hello World", "lo")'))
    assert.is_false(run('$contains("Hello World", "world")'))
  end)
  it("$split with regex", function()
    assert.are.same({ "a", "a", "xa", "cc" }, run('$split("ababbxabbcc", /b+/)'))
    assert.are.same({ "a", "b", "c" }, run('$split("a1b2c", /[0-9]/)'))
    assert.are.same({ "ababbxabbcc" }, run('$split("ababbxabbcc", /d+/)'))
  end)
  it("$split with regex + limit", function()
    assert.are.same({ "a", "a" }, run('$split("ababbxabbcc", /b+/, 2)'))
  end)
  it("$split with a string separator still works", function()
    assert.are.same({ "Hello", "World" }, run('$split("Hello World", " ")'))
  end)
end)
