local jsonata = require("jsonata")
local parser = require("jsonata.parser")
local function run(src, input)
  return jsonata.compile(src):evaluate(input)
end

describe("M7a: regex literal lexing + / disambiguation", function()
  it("parses /ab+/ as a regex node", function()
    local ast = parser.parse("/ab+/")
    assert.are.equal("regex", ast.type)
    assert.are.equal("ab+", ast.source)
    assert.are.equal("", ast.flags)
  end)
  it("captures i/m flags", function()
    assert.are.equal("i", parser.parse("/ab+/i").flags)
  end)
  it("/ after a value is division, not a regex", function()
    assert.are.equal(2, run("4/2"))
    assert.are.equal(5, run("($x := 10; $x/2)"))
    assert.are.equal(5, run("x/2", { x = 10 }))
    assert.are.equal(1, run("(1+1)/2"))
  end)
  it("empty // raises S0301", function()
    local ok, err = pcall(parser.parse, "//")
    assert.is_false(ok)
    assert.are.equal("S0301", err.code)
  end)
  it("unterminated /re raises S0302", function()
    local ok, err = pcall(parser.parse, "/unterminated")
    assert.is_false(ok)
    assert.are.equal("S0302", err.code)
  end)
  it("a closing / inside [..] does not end the regex (depth tracking)", function()
    assert.are.equal("[/]", parser.parse("/[/]/").source)
  end)
end)

describe("M7a: regex value (callable function)", function()
  it("a regex is a function value", function()
    assert.are.equal("function", run("$type(/b+/)"))
  end)
  it("applying a regex returns a match object", function()
    assert.are.equal("bb", run('($m := /b+/; $m("abbc")).match'))
  end)
  it("captures appear in groups (0-indexed array access)", function()
    assert.are.equal("bb", run('($m := /a(b+)/; $m("xabbc")).groups[0]'))
  end)
  it("the i flag is case-insensitive", function()
    assert.are.equal("Hat", run('($m := /hat/i; $m("a Hat here")).match'))
  end)
  it("no match returns undefined", function()
    assert.is_nil(run('($m := /z+/; $m("abc"))'))
  end)
end)

describe("M7a: $contains / $split with regex", function()
  it("$contains with regex", function()
    assert.is_true(run('$contains("ababbxabbcc", /ab+/)'))
    assert.is_false(run('$contains("ababbxabbcc", /ax+/)'))
    assert.is_true(run('$contains("a Hat", /hat/i)'))
  end)
  it("$contains with a string still works", function()
    assert.is_true(run('$contains("Hello World", "lo")'))
    assert.is_false(run('$contains("Hello World", "world")'))
  end)
  it("$split with regex", function()
    assert.are.same({ "a", "a", "xa", "cc" }, run('$split("ababbxabbcc", /b+/)'))
    assert.are.same({ "a", "b", "c" }, run('$split("a1b2c", /[0-9]/)'))
    assert.are.same({ "ababbxabbcc" }, run('$split("ababbxabbcc", /d+/)'))
  end)
  it("$split with regex + limit", function()
    assert.are.same({ "a", "a" }, run('$split("ababbxabbcc", /b+/, 2)'))
  end)
  it("$split with a string separator still works", function()
    assert.are.same({ "Hello", "World" }, run('$split("Hello World", " ")'))
  end)
end)

describe("M7b: H.serialize serializes function-valued object keys as empty string", function()
  it('$string of a raw match object renders next as "" (matches jsonata JSON.stringify replacer)', function()
    -- jsonata's JSON.stringify replacer maps function values to "" and keeps the key;
    -- a regex value applied to a string returns {match,start,end,groups,next} where next is a function.
    local s = run('$string(($m := /b+/; $m("abbc")))')
    assert.is_string(s)
    assert.is_truthy(s:find('"next":""'))
    assert.is_truthy(s:find('"match":"bb"'))
  end)
end)

describe("M7b: $match", function()
  it("returns an array of {match,index,groups}", function()
    assert.are.same({
      { match = "ab", index = 0, groups = { "b" } },
      { match = "abb", index = 2, groups = { "bb" } },
      { match = "abbbb", index = 5, groups = { "bbbb" } },
    }, run('$match("ababbabbbb", /a(b+)/)'))
  end)
  it("limit 1 singleton-unwraps to a single object", function()
    assert.are.same({ match = "ab", index = 0, groups = { "b" } }, run('$match("ababbabbbb", /a(b+)/, 1)'))
  end)
  it("maps over the array of matches", function()
    assert.are.same({ "ab", "abb", "abbbb" }, run('$match("ababbabbbb", /a(b+)/).match'))
  end)
  it("no match returns undefined", function()
    assert.is_nil(run('$match("xyz", /q+/)'))
  end)
  it("negative limit raises D3040", function()
    local ok, err = pcall(run, '$match("hello", /l/, -1)')
    assert.is_false(ok)
    assert.are.equal("D3040", err.code)
  end)
end)

describe("M7b: $replace", function()
  it("string pattern, literal replacement", function()
    assert.are.equal("Hello Everyone", run('$replace("Hello World", "World", "Everyone")'))
    assert.are.equal("he1lo", run('$replace("hello", "l", "1", 1)'))
  end)
  it("regex pattern with $1 group ref", function()
    assert.are.equal("-b--bb--bbbb-", run('$replace("ababbabbbb", /a(b+)/, "-$1-")'))
  end)
  it("$0 whole match and $$ literal", function()
    assert.are.equal("[ab][abb][abbbb]", run('$replace("ababbabbbb", /a(b+)/, "[$0]")'))
    assert.are.equal("f$$", run('$replace("foo", /o/, "$$")'))
    assert.are.equal("$265", run('$replace("265USD", /([0-9]+)USD/, "$$$1")'))
  end)
  it("function replacer", function()
    assert.are.equal("235", run('$replace("ababbabbbb", /a(b+)/, function($m){ $string($length($m.match)) })'))
  end)
  it("function replacer returning non-string raises D3012", function()
    local ok, err = pcall(run, '$replace("abc", /b/, function($m){ 5 })')
    assert.is_false(ok)
    assert.are.equal("D3012", err.code)
  end)
  it("empty pattern raises D3010; negative limit raises D3011", function()
    local ok1, e1 = pcall(run, '$replace("hello", "", "bye")')
    assert.is_false(ok1)
    assert.are.equal("D3010", e1.code)
    local ok2, e2 = pcall(run, '$replace("hello", /l/, "1", -2)')
    assert.is_false(ok2)
    assert.are.equal("D3011", e2.code)
  end)
end)

describe("M7b: non-participating capture group (null, not false)", function()
  it("$match groups has null for a non-participating optional group", function()
    -- $string to compare serialization: null, not false
    local s = run('$string($match("ababbabbbb", /a(xyz)?(b+)/))')
    assert.is_nil(s:find("false"))
    assert.is_truthy(s:find('%[null,"b"%]'))
  end)
  it("$replace with $N on a non-participating group yields empty (no crash)", function()
    assert.are.equal("[][][]", run('$replace("ababbabbbb", /a(xyz)?(b+)/, "[$1]")'))
  end)
end)
