local sig = require("jsonata.signature")

describe("signature: parse", function()
  it("compiles type chars into a capture-group pattern", function()
    assert.are.equal("^([nm])([nm])$", sig.parse("<nn:n>").pattern)
    assert.are.equal("^([sm])$", sig.parse("<s:s>").pattern)
  end)

  it("compiles modifiers", function()
    assert.are.equal("^([sm]?)$", sig.parse("<s-:s>").pattern)
    assert.are.equal("^([nm]?)$", sig.parse("<n?:n>").pattern)
    assert.are.equal("^([sm]+)$", sig.parse("<s+:s>").pattern)
  end)

  it("compiles array, union, subtype", function()
    assert.are.equal("^([asnblfom])$", sig.parse("<a:a>").pattern)
    assert.are.equal("^([asnblfom])([sm]?)$", sig.parse("<a<s>s?:s>").pattern)
    assert.are.equal("^([snm])$", sig.parse("<(sn):n>").pattern)
  end)

  it("raises S0401 for a subtype on a non-array/function", function()
    local ok, err = pcall(sig.parse, "<n<n>>")
    assert.is_false(ok)
    assert.are.equal("S0401", err.code)
  end)

  it("raises S0402 for a parameterized type inside a union", function()
    local ok, err = pcall(sig.parse, "<(s<n>):n>")
    assert.is_false(ok)
    assert.are.equal("S0402", err.code)
  end)

  it("maps values to type symbols", function()
    assert.are.equal("s", sig.get_symbol("hi"))
    assert.are.equal("n", sig.get_symbol(5))
    assert.are.equal("b", sig.get_symbol(true))
  end)
end)

describe("signature: validate", function()
  local function v(sigstr, args, context)
    return require("jsonata.signature").parse(sigstr).validate(args, context)
  end

  it("passes through matching args", function()
    assert.are.same({ 1, 2 }, v("<nn:n>", { 1, 2 }))
  end)

  it("raises T0410 on a type mismatch", function()
    local ok, err = pcall(v, "<nn:a>", { 1, "x" })
    assert.is_false(ok)
    assert.are.equal("T0410", err.code)
    assert.are.equal(2, err.index)
  end)

  it("raises T0410 on too many args", function()
    local ok, err = pcall(v, "<nn:a>", { 1, 2, 3 })
    assert.is_false(ok)
    assert.are.equal("T0410", err.code)
  end)

  it("injects context for a '-' param when the slot is empty", function()
    assert.are.same({ "ctx", "x" }, v("<s-s>", { "x" }, "ctx"))
    assert.are.same({ "a", "b" }, v("<s-s>", { "a", "b" }, "ctx"))
  end)

  it("raises T0411 when the context type is incompatible", function()
    local ok, err = pcall(v, "<s-s>", { "x" }, 5)
    assert.is_false(ok)
    assert.are.equal("T0411", err.code)
  end)

  it("wraps a scalar into a single-element array for an 'a' param", function()
    local V = require("jsonata.value")
    local r = v("<a:a>", { "x" })
    assert.is_true(V.is_array(r[1]))
    assert.are.equal("x", r[1][1])
  end)

  it("raises T0412 on a wrong array subtype", function()
    local ok, err = pcall(v, "<a<n>:a>", { { "s" } })
    assert.is_false(ok)
    assert.are.equal("T0412", err.code)
  end)
end)
