local V = require("jsonata.value")

describe("value: sentinels", function()
  it("NULL and NOTHING are distinct singletons", function()
    assert.is_true(V.is_null(V.NULL))
    assert.is_true(V.is_nothing(V.NOTHING))
    assert.is_false(V.is_null(V.NOTHING))
    assert.is_false(V.is_nothing(V.NULL))
    assert.is_false(V.is_null(nil))
    assert.is_false(V.is_nothing(nil))
  end)
end)

describe("value: arrays", function()
  it("constructs and detects arrays", function()
    local a = V.array({ 1, 2, 3 })
    assert.is_true(V.is_array(a))
    assert.are.equal(3, #a)
    assert.is_false(V.is_array({ 1, 2, 3 }))
  end)
end)

describe("value: sequences", function()
  it("constructs sequences with elements", function()
    local s = V.sequence(10, 20)
    assert.is_true(V.is_sequence(s))
    assert.is_true(V.is_array(s))
    assert.are.equal(2, #s)
    assert.are.equal(10, s[1])
  end)

  it("supports flags without affecting length", function()
    local s = V.sequence(7)
    V.set_flag(s, "keepSingleton", true)
    assert.is_true(V.get_flag(s, "keepSingleton"))
    assert.are.equal(1, #s)
  end)
end)

describe("value: ordered objects", function()
  it("preserves key insertion order", function()
    local o = V.object()
    V.obj_set(o, "b", 1)
    V.obj_set(o, "a", 2)
    V.obj_set(o, "c", 3)
    assert.is_true(V.is_object(o))
    assert.are.same({ "b", "a", "c" }, V.obj_keys(o))
    assert.are.equal(2, V.obj_get(o, "a"))
  end)

  it("does not duplicate keys on update and returns NOTHING for missing", function()
    local o = V.object()
    V.obj_set(o, "x", 1)
    V.obj_set(o, "x", 9)
    assert.are.same({ "x" }, V.obj_keys(o))
    assert.are.equal(9, V.obj_get(o, "x"))
    assert.is_true(V.is_nothing(V.obj_get(o, "missing")))
  end)

  it("stores NULL values as present", function()
    local o = V.object()
    V.obj_set(o, "n", V.NULL)
    assert.is_true(V.is_null(V.obj_get(o, "n")))
  end)
end)

describe("value: typeof", function()
  it("classifies all value kinds", function()
    assert.are.equal("null", V.typeof(V.NULL))
    assert.are.equal("nothing", V.typeof(V.NOTHING))
    assert.are.equal("number", V.typeof(3))
    assert.are.equal("string", V.typeof("s"))
    assert.are.equal("boolean", V.typeof(true))
    assert.are.equal("array", V.typeof(V.array({})))
    assert.are.equal("array", V.typeof(V.sequence()))
    assert.are.equal("object", V.typeof(V.object()))
    assert.are.equal("function", V.typeof(function() end))
  end)
end)
